# Generated by Django 5.1.2 on 2024-11-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
