# Generated by Django 5.1.3 on 2024-11-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_autor_cpf_autor_data_nasc_autor_email_autor_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitor',
            name='cpf',
            field=models.CharField(max_length=100, unique=True, verbose_name='CPF do leitor'),
        ),
    ]
