# Generated by Django 5.1.3 on 2024-11-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_autor_telefone_alter_editora_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='cpf',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default='', max_length=255),
        ),
    ]
